version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - 3000:3000
    environment:
      MONGO_URI: "mongodb://root:example@mongo"
      MONGO_DB: "admin"
      MAILER_TRANSPORT_HOST: "mailhog"
      MAILER_TRANSPORT_PORT: 1025
      MAILER_TRANSPORT_AUTH_USER: "root"
      MAILER_TRANSPORT_AUTH_PASS: "root"
      MAILER_FROM_DEFAULT: "hello@abc.xyz"
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
